Fixed BB-127, BB-139
talerqa/inctagram_blazing_bonfires pull request #56
Opened 2024-02-18 11:37 UTC by h12t20

Таски объединены поскольку речь идет об одном элементе - инпуте). Инпут приведен в соответствие с figma. Также устранены некоторые потенциальные проблемы инпута, которые могли проявиться в дальнейшем. В связи с тем, что изменилось позиционирование элемента на странице (устранена зависимость от наличия у инпута заголовка и ошибки) , внесены изменения в некоторые формы, чтобы привести их в соответствие с figma. Нуждается в тестировании.

2024-02-18 21:37 UTC, beamle requested changes
Привет, чекни мой пулл реквест, там пару добавлений имеется.

2024-02-19 17:23 UTC, dezo103 approved these changes

2024-02-19 17:32 UTC, h12t20 commented
> Привет, чекни мой пулл реквест, там пару добавлений имеется.

Спасибо. Одобрено.

2024-02-19 17:47 UTC, beamle approved these changes

2024-02-19 18:41 UTC, merged